version: "{build}"

# Source Config
clone_folder: c:\gopath\src\github.com\golang\nest

# Build host

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.7

init:
  - git config --global core.autocrlf input

# Build

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=c:\go\bin;c:\gopath\bin;%Path%
  - go version
  - go env

build: false
deploy: false

test_script:
  - go build
  - go test
