version: "{build}"

# Source Config
clone_folder: c:\gopath\src\github.com\golang\dep

# Build host

environment:
  GOPATH: c:\gopath
  matrix:
    - environment:
      GOVERSION: 1.7.5
    - environment:
      GOVERSION: 1.8

init:
  - git config --global core.autocrlf input

# Build

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=c:\go\bin;c:\gopath\bin;%Path%
  - go version
  - go env

build: false
deploy: false

test_script:
  - go build
  - go test .
  - go test ./cmd/dep
  - go test ./gps
  - go test ./gps/internal
  - go test ./gps/internal/fs
  - go test ./gps/pkgtree
  - go test ./internal
  - go test ./test
